# These options are ones you can pass as command line arguments
# e.g., $ neovide --frame buttonless --title-hidden
frame = "transparent"
title-hidden = true

# These are runtime options
[font]
normal = ["FantasqueSansM Nerd Font", "ComicCodeLigatures Nerd Font"] # Will use the bundled Fira Code Nerd Font by default
size = 15.0
